### ISSUE TITLE
パフォーマンス解消

### ISSUE THREAD

**Issue by PenPeen** [PenPeen/rails7_instagram_parody#14]
post.user でN＋1？

```
  Rendered posts/_like_text.html.erb (Duration: 19.9ms | Allocations: 859)
  CACHE User Load (0.0ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 11 LIMIT 1
  ↳ app/views/posts/_post.html.erb:5
  Like Load (2.0ms)  SELECT `likes`.* FROM `likes` WHERE `likes`.`user_id` = 11 AND `likes`.`post_id` = 9 LIMIT 1
  ↳ app/models/post.rb:11:in `liked_by'
  Like Load (0.8ms)  SELECT `likes`.* FROM `likes` WHERE `likes`.`post_id` = 9 ORDER BY `likes`.`created_at` DESC
  ↳ app/views/posts/_like_text.html.erb:2
  Rendered posts/_like_text.html.erb (Duration: 14.2ms | Allocations: 860)
  CACHE User Load (0.0ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 11 LIMIT 1
  ↳ app/views/posts/_post.html.erb:5
  Like Load (0.6ms)  SELECT `likes`.* FROM `likes` WHERE `likes`.`user_id` = 11 AND `likes`.`post_id` = 8 LIMIT 1
  ↳ app/models/post.rb:11:in `liked_by'
  Like Load (1.3ms)  SELECT `likes`.* FROM `likes` WHERE `likes`.`post_id` = 8 ORDER BY `likes`.`created_at` DESC
  ↳ app/views/posts/_like_text.html.erb:2
```

**Comment by PenPeen** [comment]
解消しました。
[Link](https://github.com/PenPeen/rails7_instagram_parody/commit/bcdc893c70e64eeae50fa8d609b736745c8b91c3)
